# Change these first
owner: SergioRugiero # Your GitHub username
repo: UptimeDropit # Your Github repository name

# Add your sites here
sites:
  - name: Pickit Argentina  
    url: https://www.pickit.com.ar

  - name: Pickit Argentina Admin
    url: https://admin.pickit.net/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Argentina Comercio
    url: https://comercio.pickit.net/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Argentina Punto
    url: https://punto.pickit.net/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Colombia
    url: https://www.pickit.com.co

  - name: Pickit Colombia Admin
    url: https://admin.pickit.com.co/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Colombia Comercio
    url: https://comercio.pickit.com.co/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Colombia Punto
    url: https://punto.pickit.com.co/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Mexico
    url: https://www.pickit.com.mx

  - name: Pickit Mexico Admin
    url: https://admin.pickit.com.mx/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Mexico Comercio
    url: https://comercio.pickit.com.mx/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Mexico Punto
    url: https://punto.pickit.com.mx/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Uruguay 
    url: https://www.pickit.com.uy


  - name: Pickit Uruguay Admin
    url: https://admin.pickit.com.uy/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Uruguay Comercio
    url: https://comercio.pickit.com.uy/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Uruguay Punto
    url: https://punto.pickit.com.uy/
    expectedStatusCodes:
      - 200
      - 201

  - name: Pickit Jira
    url: http://support.pickit.net

  - name: Pickit Odoo
    url: https://odoo.pickit.net/web/login

  - name: Pickit México Admin
    url: https://admin.pickit.com.mx/
    expectedStatusCodes:
      - 200
      - 201

  - name: Secret Site
    url: $SECRET_SITE
    expectedStatusCodes:
     - 200
     - 401

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /UptimeDropit
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
