# Change these first
owner: SergioRugiero # Your GitHub username
repo: UptimeDropit # Your Github repository name

# Add your sites here
sites:
  - name: Pickit Argentina  
    url: https://www.pickit.com.ar
  - name: Pickit Colombia
    url: https://www.pickit.com.co
  - name: Pickit Mexico
    url: https://www.pickit.com.mx
  - name: Pickit Uruguay 
    url: https://www.pickit.com.uy
  - name: Pickit Jira
    url: http://support.pickit.net
  - name: Pickit Odoo
    url: https://odoo.pickit.net
    
status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  # Uncomment the following line if you don't have a custom domain and add your repo name
  baseUrl: /UptimeDropit
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [Github repository](https://github.com/koj-co/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/koj-co/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
